@startuml

package web {}

package supplements <<rectangle>> {

    package controls {}
    package facades {}

}

package dataflow <<rectangle>> {

    package core {}

    package connector <<rectangle>> {
        package connector_base {}
        package connector_builtin {}
        package connector_protocols {}
    }


    package component <<rectangle>> {
        package component_base {}
        package component_builtin {}
        package component_protocols {}
    }

    package actors {}

    package designer {}

}

actors --> core
actors --> connector_base
designer --> controls
designer --> facades
designer --> core
designer --> component_base
designer --> component_builtin
designer --> connector_base
designer --> connector_builtin
connector_base --> controls
connector_base --> core
connector_builtin --> controls
connector_builtin --> facades
connector_builtin --> core
connector_builtin --> connector_base
connector_builtin --> connector_protocols
connector_protocols --> connector_base
component_base --> controls
component_base --> facades
component_base --> core
component_base --> connector_base
component_builtin --> controls
component_builtin --> facades
component_builtin --> core
component_builtin --> connector_base
component_builtin --> component_base
component_builtin --> component_protocols
component_protocols --> core
component_protocols --> connector_base
controls --> facades
web --> core
web --> actors
web --> connector_base
web --> connector_protocols
web --> component_protocols

@enduml